'use strict';
const { now, plainObject, beforeDeadline, beginDeadline, remainingMs, scores, migrateIdentity } = require('./_shared');
const ROUNDS=3,DURATION=8000,COUNTDOWN=3000,RESULT=4000,BURST=8,SUSTAINED_PER_SEC=16;
module.exports={id:'tap-frenzy',name:'Tap Frenzy',description:'Tap like your life depends on it! Most taps wins.',icon:'👆',minPlayers:2,maxPlayers:20,rounds:ROUNDS,roundDuration:DURATION,
init(room,io){room.gameState={round:0,roundId:0,totalRounds:ROUNDS,phase:'waiting',taps:new Map(),limits:new Map(),resultState:null};room._tfTimers=[];room._tfIntervals=[];this._nextRound(room,io);},
_timer(room,fn,ms){const t=setTimeout(fn,ms);room._tfTimers.push(t);return t;},
_nextRound(room,io){const gs=room.gameState;gs.round++;gs.roundId++;if(gs.round>gs.totalRounds)return this._endGame(room,io);gs.taps=new Map(Array.from(room.players.keys(),id=>[id,0]));gs.limits=new Map();gs.resultState=null;gs.phase='countdown';const token=gs.roundId;io.to(room.code).emit('game:state',{phase:'countdown',round:gs.round,totalRounds:gs.totalRounds,roundId:token});this._timer(room,()=>{if(gs.roundId!==token||gs.phase!=='countdown')return;gs.phase='tapping';beginDeadline(room,gs,DURATION);io.to(room.code).emit('game:state',{phase:'tapping',roundId:token,duration:DURATION});const tick=setInterval(()=>{if(gs.phase!=='tapping')return clearInterval(tick);io.to(room.code).emit('game:tick',{counts:this._counts(room)});},500);room._tfIntervals.push(tick);this._timer(room,()=>{if(gs.roundId===token&&gs.phase==='tapping')this._roundResult(room,io);},DURATION);},COUNTDOWN);},
_counts(room){return Array.from(room.gameState.taps,([id,count])=>({id,name:room.players.get(id)?.name||'Unknown',count})).sort((a,b)=>b.count-a.count||a.id.localeCompare(b.id));},
onEvent(room,socket,event,data){const gs=room.gameState;if(event!=='tap'||gs.phase!=='tapping'||!beforeDeadline(room,gs)||(data!==undefined&&!plainObject(data)))return{ok:false,code:'INVALID_ACTION'};if(data?.roundId!==undefined&&data.roundId!==gs.roundId)return{ok:false,code:'STALE_ROUND'};const p=room.players.get(socket.id);if(!p||p.disconnected)return{ok:false,code:'INELIGIBLE'};const at=now(room),state=gs.limits.get(socket.id)||{tokens:BURST,last:at};state.tokens=Math.min(BURST,state.tokens+(at-state.last)*SUSTAINED_PER_SEC/1000);state.last=at;if(state.tokens<1){gs.limits.set(socket.id,state);return{ok:false,code:'RATE_LIMITED'};}state.tokens--;gs.limits.set(socket.id,state);gs.taps.set(socket.id,(gs.taps.get(socket.id)||0)+1);return{ok:true};},
_roundResult(room,io){const gs=room.gameState;if(gs.phase!=='tapping')return;gs.phase='result';(room._tfIntervals||[]).forEach(clearInterval);room._tfIntervals=[];const results=this._counts(room),tables=[150,100,75];let rank=0;for(let i=0;i<results.length;){let j=i+1;while(j<results.length&&results[j].count===results[i].count)j++;const count=results[i].count;const pool=count>0?results.slice(i,j).reduce((n,_,offset)=>n+(tables[i+offset]||25),0):0;const points=count>0?Math.round(pool/(j-i)):0;for(let k=i;k<j;k++){results[k].rank=count>0?rank+1:null;results[k].points=points;const p=room.players.get(results[k].id);if(p)p.score=(p.score||0)+points;}if(count>0)rank+=j-i;i=j;}gs.resultState={phase:'result',round:gs.round,totalRounds:gs.totalRounds,roundId:gs.roundId,results};io.to(room.code).emit('game:state',gs.resultState);const token=gs.roundId;this._timer(room,()=>{if(gs.roundId===token&&gs.phase==='result')this._nextRound(room,io);},RESULT);},
_endGame(room,io){if(room.gameState.phase==='finished')return;room.gameState.phase='finished';io.to(room.code).emit('game:end',{scores:scores(room)});room.state='results';},
getReconnectState(room,playerId){const gs=room.gameState;if(!gs)return null;if(gs.phase==='countdown')return{phase:'countdown',round:gs.round,totalRounds:gs.totalRounds,roundId:gs.roundId};if(gs.phase==='tapping')return{phase:'tapping',round:gs.round,totalRounds:gs.totalRounds,roundId:gs.roundId,duration:remainingMs(room,gs),count:gs.taps.get(playerId)||0,counts:this._counts(room)};if(gs.phase==='result')return{...gs.resultState};return null;},
migratePlayerIdentity(room,oldId,newId){migrateIdentity(room.gameState,oldId,newId,{maps:['taps','limits']});for(const r of room.gameState?.resultState?.results||[])if(r.id===oldId)r.id=newId;},
getBotMove(room,bot){const gs=room.gameState;if(!gs||gs.phase!=='tapping')return null;return{event:'tap',data:{roundId:gs.roundId}};},
cleanup(room){(room._tfTimers||[]).forEach(clearTimeout);(room._tfIntervals||[]).forEach(clearInterval);room._tfTimers=[];room._tfIntervals=[];}};
