'use strict';
// Type Racer — exact-text, server-monotonic receipt-authoritative race.
const { now, rng, plainObject, boundedString, beforeDeadline, beginDeadline, remainingMs, scores, migrateIdentity, allActiveHave } = require('./_shared');
const ROUND_TIME = 30000, ROUNDS = 5, RESULT_DELAY = 3500, MAX_WPM = 240, PROGRESS_MIN_MS = 100;
const SENTENCE_POOL = [
  'The quick brown fox jumps over the lazy dog','Pack my box with five dozen liquor jugs','How vexingly quick daft zebras jump','The five boxing wizards jump quickly','Sphinx of black quartz judge my vow','Bright vixens jump dozy fowl quack','Jackdaws love my big sphinx of quartz','The job requires extra pluck and zeal from every young wage earner','A wizard quickly jinxed the gnomes before they vaporized','Two driven jocks help fax my big quiz','Fix problem quickly with galvanized jets','Heavy boxes perform quick waltzes and jigs','We promptly judged antique ivory buckles for the next prize','Crazy Fredrick bought many very exquisite opal jewels','Sixty zippers were quickly picked from the woven jute bag'
];
function pickSentences(count, random) { const pool = [...SENTENCE_POOL], out = []; while (out.length < count && pool.length) out.push(pool.splice(Math.floor(random() * pool.length), 1)[0]); return out; }
function score(sentence, elapsed) { const rawWpm = (sentence.length / 5) / (Math.max(1, elapsed) / 60000); const anomaly = rawWpm > MAX_WPM; const wpm = Math.min(MAX_WPM, Math.max(0, Math.round(rawWpm))); return { wpm, accuracy: 1, score: wpm, anomaly }; }
function correctPrefix(sentence, typed) { let i = 0; while (i < typed.length && i < sentence.length && typed[i] === sentence[i]) i++; return i; }
module.exports = {
  id:'type-racer', name:'Type Racer', description:'Race to type the sentence — speed and accuracy both matter!', icon:'⌨️', minPlayers:2, maxPlayers:20, rounds:ROUNDS,
  init(room, io) { room.gameState={round:0,roundId:0,totalRounds:ROUNDS,phase:'waiting',sentences:pickSentences(ROUNDS,()=>rng(room)),progress:new Map(),finishers:[],resultState:null}; room._trTimers=[]; this._nextRound(room,io); },
  _timer(room,fn,ms,interval=false){const t=(interval?setInterval:setTimeout)(fn,ms);(room._trTimers||=[]).push(t);return t;},
  _nextRound(room,io){const gs=room.gameState;gs.round++;gs.roundId++;if(gs.round>gs.totalRounds)return this._endGame(room,io);gs.phase='typing';gs.progress=new Map();gs.finishers=[];gs.resultState=null;beginDeadline(room,gs,ROUND_TIME);const token=gs.roundId,sentence=gs.sentences[gs.round-1];io.to(room.code).emit('game:state',{phase:'typing',round:gs.round,totalRounds:gs.totalRounds,roundId:token,sentence,timeLimit:ROUND_TIME});this._timer(room,()=>{if(gs.roundId===token&&gs.phase==='typing')this._roundResult(room,io);},ROUND_TIME);},
  onEvent(room,socket,event,data,io){const gs=room.gameState;if(!gs||gs.phase!=='typing'||!beforeDeadline(room,gs))return{ok:false,code:'NOT_OPEN'};if(!plainObject(data)||Object.keys(data).length!==2||!boundedString(data.typed,512)||!Number.isSafeInteger(data.roundId))return{ok:false,code:'INVALID_PAYLOAD'};if(data.roundId!==gs.roundId)return{ok:false,code:'STALE_ROUND'};const sentence=gs.sentences[gs.round-1],player=room.players.get(socket.id);if(!player||player.disconnected)return{ok:false,code:'INELIGIBLE'};
    if(event==='progress'){const previous=gs.progress.get(socket.id),at=now(room);if(previous&&at-previous.at<PROGRESS_MIN_MS)return{ok:false,code:'RATE_LIMITED'};const prefix=correctPrefix(sentence,data.typed);if(previous&&prefix<previous.prefix)return{ok:false,code:'REGRESSION'};gs.progress.set(socket.id,{typed:data.typed.slice(0,prefix),prefix,pct:prefix/sentence.length,at});const players=Array.from(room.players,([id,p])=>({id,name:p.name,pct:gs.progress.get(id)?.pct||0,finished:gs.finishers.some(f=>f.id===id)}));io.to(room.code).emit('game:progress',{players});return{ok:true};}
    if(event!=='finish')return{ok:false,code:'UNKNOWN_EVENT'};if(gs.finishers.some(f=>f.id===socket.id))return{ok:false,code:'DUPLICATE'};if(data.typed!==sentence)return{ok:false,code:'INCORRECT'};const elapsed=Math.max(1,now(room)-gs.phaseStartedAt),metrics=score(sentence,elapsed),position=gs.finishers.length,bonus=[50,30,10][position]||0,totalPoints=metrics.score+bonus;player.score=(player.score||0)+totalPoints;const finisher={id:socket.id,name:player.name,wpm:metrics.wpm,accuracy:1,score:totalPoints,elapsed:Math.round(elapsed),correct:true,anomaly:metrics.anomaly};gs.finishers.push(finisher);gs.progress.set(socket.id,{typed:sentence,prefix:sentence.length,pct:1,at:now(room)});socket.emit('game:state',{phase:'finished-round',wpm:metrics.wpm,accuracy:1,score:totalPoints,position:position+1,correct:true,anomaly:metrics.anomaly});if(allActiveHave(room,new Set(gs.finishers.map(f=>f.id))))this._timer(room,()=>{if(gs.phase==='typing')this._roundResult(room,io);},1500);return{ok:true};},
  _roundResult(room,io){const gs=room.gameState;if(gs.phase!=='typing')return;gs.phase='result';gs.resultState={phase:'result',round:gs.round,totalRounds:gs.totalRounds,roundId:gs.roundId,finishers:gs.finishers.map(x=>({...x})),sentence:gs.sentences[gs.round-1]};io.to(room.code).emit('game:state',gs.resultState);const token=gs.roundId;this._timer(room,()=>{if(gs.roundId===token&&gs.phase==='result')this._nextRound(room,io);},RESULT_DELAY);},
  _endGame(room,io){if(room.gameState.phase==='finished')return;room.gameState.phase='finished';io.to(room.code).emit('game:end',{scores:scores(room)});room.state='results';},
  getReconnectState(room,playerId){const gs=room.gameState;if(!gs)return null;if(gs.phase==='typing')return{phase:'typing',round:gs.round,totalRounds:gs.totalRounds,roundId:gs.roundId,sentence:gs.sentences[gs.round-1],timeLimit:remainingMs(room,gs),finished:gs.finishers.some(f=>f.id===playerId),progress:gs.progress.get(playerId)?.pct||0};if(gs.phase==='result')return{...gs.resultState};return null;},
  migratePlayerIdentity(room,oldId,newId){migrateIdentity(room.gameState,oldId,newId,{maps:['progress'],objectArrays:['finishers']});if(room.gameState?.resultState)(room.gameState.resultState.finishers||[]).forEach(f=>{if(f.id===oldId)f.id=newId;});},
  getBotMove(room,bot){const gs=room.gameState;if(!gs||gs.phase!=='typing'||gs.finishers.some(f=>f.id===bot.id))return null;return{event:'finish',data:{typed:gs.sentences[gs.round-1],roundId:gs.roundId}};},
  cleanup(room){(room._trTimers||[]).forEach(t=>{clearTimeout(t);clearInterval(t);});room._trTimers=[];}
};
