const { chromium } = require('/tmp/afgqa/node_modules/playwright');
const assert = require('assert');
const path = require('path');
const out = path.join(__dirname, 'screenshots');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const errors=[];
  const desktop=await browser.newPage({viewport:{width:1440,height:900}});
  desktop.on('console',m=>{if(m.type()==='error')errors.push(`desktop console: ${m.text()}`)});
  desktop.on('pageerror',e=>errors.push(`desktop pageerror: ${e.message}`));
  await desktop.goto('http://localhost:3014/play/?e2e=desktop',{waitUntil:'networkidle'});
  assert.strictEqual(await desktop.locator('#connection-status').getAttribute('class'),'connection-status','initial connection must not show recovery badge');
  assert.strictEqual(await desktop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'desktop horizontal overflow');
  await desktop.screenshot({path:path.join(out,'arcade-field-guide-desktop.png'),fullPage:true});
  await desktop.getByLabel('Your field name').fill('Pointer QA');
  await desktop.getByRole('button',{name:/Create a room/}).click();
  const reaction=desktop.getByRole('radio',{name:/Reaction Race/});
  await reaction.scrollIntoViewIfNeeded();
  await reaction.click();
  assert.strictEqual(await reaction.getAttribute('aria-checked'),'true','pointer selection did not check Reaction Race');
  assert.strictEqual(await desktop.getByRole('button',{name:'Start selected game'}).isEnabled(),true,'pointer selection did not enable Start');
  await reaction.press('ArrowRight');
  const simon=desktop.getByRole('radio',{name:/Simon Says/});
  assert.strictEqual(await simon.getAttribute('aria-checked'),'true','keyboard arrow did not select Simon Says');
  assert.strictEqual(await desktop.evaluate(()=>document.activeElement?.dataset?.gameId),'simon-says','keyboard selection did not move focus');
  await simon.press('Home');
  assert.strictEqual(await desktop.getByRole('radio',{name:/Color Clash/}).getAttribute('aria-checked'),'true','Home did not select first radio');
  await desktop.screenshot({path:path.join(out,'arcade-field-guide-lobby-desktop.png'),fullPage:true});

  const mobile=await browser.newPage({viewport:{width:375,height:667},isMobile:true,hasTouch:true});
  mobile.on('console',m=>{if(m.type()==='error')errors.push(`mobile console: ${m.text()}`)});
  mobile.on('pageerror',e=>errors.push(`mobile pageerror: ${e.message}`));
  await mobile.goto('http://localhost:3014/play/?e2e=mobile',{waitUntil:'networkidle'});
  const createBox=await mobile.getByRole('button',{name:/Create a room/}).boundingBox();
  assert(createBox && createBox.y+createBox.height<=667,`mobile primary action below fold: ${JSON.stringify(createBox)}`);
  assert.strictEqual(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile horizontal overflow');
  const targets=await mobile.locator('button,input').evaluateAll(els=>els.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&(r.width<44||r.height<44)}).map(e=>({id:e.id,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));
  assert.deepStrictEqual(targets,[],'mobile controls below 44px');
  await mobile.screenshot({path:path.join(out,'arcade-field-guide-mobile.png'),fullPage:true});
  await mobile.getByLabel('Your field name').fill('Touch QA');
  await mobile.getByRole('button',{name:/Create a room/}).tap();
  const mobileReaction=mobile.getByRole('radio',{name:/Reaction Race/});
  await mobileReaction.scrollIntoViewIfNeeded();
  await mobileReaction.tap();
  assert.strictEqual(await mobileReaction.getAttribute('aria-checked'),'true','touch selection did not check Reaction Race');
  assert.strictEqual(await mobile.getByRole('button',{name:'Start selected game'}).isEnabled(),true,'touch selection did not enable Start');
  assert.strictEqual(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile lobby horizontal overflow');
  await mobile.screenshot({path:path.join(out,'arcade-field-guide-lobby-mobile.png'),fullPage:true});
  await browser.close();
  assert.deepStrictEqual(errors,[],'browser console errors');
  console.log('Browser smoke passed: pointer, touch, keyboard radios; initial status; 44px targets; above-fold CTA; desktop/mobile overflow and screenshots.');
})().catch(e=>{console.error(e);process.exit(1)});
